### ISSUE TITLE
Can I use it in Objective-C project 

### ISSUE THREAD

**Issue by YBENZAKOUR** [sh-khashimov/SwiftFortuneWheel#17]
Hello, Can I use 'SwiftFortuneWheel' in my objective-C project, Thanks for your reply

**Comment by sh-khashimov** [comment]
Unfortunately, since SwiftFortuneWheel heavily uses Structs, it's not possible to use it directly on the Objective-C project.
You have to create a bridge as a custom view using the .swift file in your project. 
Add SwiftFortuneWheel to that custom view.
Use your swift custom view in your objective-c project.
